SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, (precio * 1.21) FROM producto;
SELECT nombre AS 'nom de producto', precio AS 'euro', (precio * 1.21) AS 'dolars' FROM producto;
SELECT upper(nombre) as 'nom', precio FROM producto;
SELECT lower(nombre) as 'nom', precio FROM producto;
SELECT nombre, upper(LEFT(nombre, 2)) as 'nom' FROM fabricante;
SELECT nombre, round(precio, 1) FROM producto;
SELECT nombre, truncate(precio, 0) FROM producto;
SELECT producto.codigo_fabricante FROM producto, fabricante WHERE producto.codigo_fabricante =  fabricante.codigo ;
SELECT DISTINCT producto.codigo_fabricante FROM producto, fabricante WHERE producto.codigo_fabricante =  fabricante.codigo ;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto, fabricante WHERE producto.codigo_fabricante = fabricante.codigo; 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto, fabricante WHERE producto.codigo_fabricante = fabricante.codigo ORDER BY fabricante.nombre;
SELECT producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre FROM producto, fabricante WHERE producto.codigo_fabricante = fabricante.codigo; 
SELECT producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre FROM producto, fabricante WHERE producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio LIMIT 1; 
SELECT producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre FROM producto, fabricante WHERE producto.codigo_fabricante = fabricante.codigo ORDER BY producto.precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') = codigo_fabricante;
SELECT nombre FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Crucial') = codigo_fabricante AND precio > 200;
SELECT nombre FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Asus') = codigo_fabricante OR (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard') = codigo_fabricante OR (SELECT codigo FROM fabricante WHERE nombre = 'Seagate') = codigo_fabricante;
SELECT producto.nombre FROM producto, fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT nombre, precio FROM producto WHERE nombre LIKE '%e';
SELECT nombre, precio FROM producto WHERE nombre LIKE '%w%';
SELECT producto.nombre, producto.precio, fabricante.nombre FROM producto, fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND precio >= 180 ORDER BY producto.precio DESC, producto.nombre;
SELECT DISTINCT producto.codigo_fabricante, fabricante.nombre FROM fabricante, producto WHERE producto.codigo_fabricante = fabricante.codigo;
SELECT fabricante.nombre, producto.nombre FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante = fabricante.codigo;
SELECT fabricante.nombre, producto.nombre FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante = fabricante.codigo WHERE producto.nombre IS NULL;
SELECT nombre, precio FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') = codigo_fabricante;
SELECT * FROM producto WHERE precio = (SELECT precio FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') = codigo_fabricante ORDER BY precio DESC LIMIT 1);
SELECT nombre FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') = codigo_fabricante ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard') = codigo_fabricante ORDER BY precio LIMIT 1;
SELECT * FROM producto WHERE precio = (SELECT precio FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') = codigo_fabricante ORDER BY precio DESC LIMIT 1);
SELECT nombre FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Asus') = codigo_fabricante AND precio > (SELECT AVG(precio) FROM producto WHERE (SELECT codigo FROM fabricante WHERE nombre = 'Asus') = codigo_fabricante);